### PR TITLE
Ascii Support for download or copy paste

### PR DESCRIPTION
**Pull request by agundy**
WARNING: Breaks backwards. Database needs to have filedata stripped of the leading ""data:application/octet-stream;base64," and then have a replace of  "str.replace(/+/g, '-').replace(/\//g, '_')" and then stored as the ASCII Field. Also removed preliminary angular cruft and added title to the page.

### CODE REVIEW

**Comment by lukechampine** [comment]
Can you explain what this does in more detail? Are you replacing binary .sia files with ASCII, or are you supporting both?

**Comment by agundy** [comment]
Binary files are converted into the ascii encoding. which is just a conversion to base64 encoding. then to download the files there is a conversion to data url format which is base64 with a header and two simple string replaces. Letting us store the ascii and a downloadable version of the .sia file in one db field.

**Comment by DavidVorick** [comment]
in what way is compatibility broken? And is there a way to preserve it, or are we going to need some sort of database migration script?

**Comment by agundy** [comment]
Database currently doesn't have anything in the ASCII field. Also the data url encoding will need to be switched over. We should probably have some upgrade task for the db.

**Comment by DavidVorick** [comment]
Does the ascii field need to be in the database? I feel like you could just take the '.sia' and generate the ascii on the fly

**Comment by agundy** [comment]
the .sia is currently stored as a base64 encoded string anyway so not much different. It's easier to go from ascii with no header data to dataurl than from dataurl to ascii though so that was why I went with this method.

**Comment by DavidVorick** [comment]
oh. Do you have to store it as base64? That's really inefficient

**Comment by agundy** [comment]
It's not super inefficient only a 33% overhead and one of the best ways to represent the binary data in json. We also have to convert to it for both downloading and copying so imo it's not a bad idea to keep it as base64

**Pull request merged**
