### PR TITLE
added makefile

### PR DESCRIPTION
**Pull request by agundy**
Inspired by @Mingling94's Makefile

### CODE REVIEW

**Comment by DavidVorick** [comment]
This is a bad makefile :)

all should assume that you have all of the dependencies and should build the project.

```
all: install

install:
    go install ./...
```

Otherwise it looks fine.

**Comment by lukechampine** [comment]
The `go` command was designed to obviate the need for simple Makefiles. In this case there isn't a clear reason to have a Makefile; not yet at least. Even in Sia, the Makefile is really just a set of convenient aliases.

**Comment by DavidVorick** [comment]
I really like Makefiles. But Luke is right, Sia really only needs one because we use a lot of tags and have a lot of packages, and it makes running certain commands easier.

This makefile does a lot less, mostly it just brings greater accessibility to people familiar with Make but not with golang.

**Comment by agundy** [comment]
I can close this. It was just an quick makefile.

**Comment by DavidVorick** [comment]
:p

**Comment by Mingling94** [comment]
YEAH AARON, let that be a lesson to you!

**Comment by DavidVorick** [comment]
(try to keep it professional)

**Pull request closed without merging**
